language: node_js
node_js:
  - "10"
before_install:
  - npm install -g sfdx-cli
before_script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "$SFDX_AUTH_URL" > /tmp/sfdxurl; sfdx force:auth:sfdxurl:store -f /tmp/sfdxurl -a ci-devhub -d; fi
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sfdx force:org:delete --noprompt -u ci-scratch-org; fi
script:
  - sfdx plugins:link .
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sfdx force:org:create -f config/project-scratch-def.json -a ci-scratch-org -s; fi
  - npm test
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run test:plugins; fi
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: "10"
      script:
        - npm install --global semantic-release@15
        - semantic-release
