version: 2
jobs:
  test:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          command: yarn
          no_output_timeout: 30m
      - run: yarn run test
  e2e:
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
      - run: ls
      - run: sudo npm install -g sfdx-cli yarn
      - run:
          command: yarn
          no_output_timeout: 30m
      - run: echo "$SFDX_AUTH_URL" > /tmp/sfdxurl
      - run: sfdx force:auth:sfdxurl:store -f /tmp/sfdxurl -a ci-devhub -d
      - run: sfdx force:org:create -f config/project-scratch-def.json -a ci-scratch-org -s
      - run: yarn run test:e2e
      - run:
          command: sfdx force:org:delete --noprompt -u ci-scratch-org || true
          when: always
  # release:
  #   docker:
  #     - image: circleci/node:11
  #   steps:
  #     - checkout
  #     - run: sudo npm install --global semantic-release@15
  #     - run: semantic-release
workflows:
  version: 2
  test-and-release:
    jobs:
      - test
      - e2e
      # - release:
      #     requires:
      #       - test
      #       - e2e
      #     filters:
      #       branches:
      #         only: master
