name: Test Salesforce Preview Release

on:
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          yarn install
          yarn global add sfdx-cli@7.172.0
      - name: Run unit tests
        run: yarn test
      - name: Authenticate DevHub and create scratch org
        env:
          SFDX_AUTH_URL_DEVHUB: ${{ secrets.SFDX_AUTH_URL_DEVHUB }}
        run: |
          sfdx auth:sfdxurl:store -d -a devhub -f /dev/stdin <<< "${SFDX_AUTH_URL_DEVHUB}"
          yarn develop release=preview
      - name: Run end-to-end tests
        run: yarn test:e2e
      - name: Delete scratch org
        if: always()
        run: |
          sfdx force:org:delete -p
